#!/usr/bin/env python3
"""Write experiment 1's three evaluation sweeps from the six search results.

Pre-registered at `docs/preregistration/searched-s3-pursuer.md` (577f15a).

The six searched rows' constants are read out of `results/search_s3_pursuer_*.json`
rather than typed, because a transcription error in a six-constant table is
invisible: the row would still run, still aggregate, still produce a survival
number, and nothing downstream would notice it was not the controller the search
returned. The generated configs are committed — they are the record — and this
script is how they were produced and how they are checked.

    python scripts/build_pursuer_searched_s3_configs.py           write all three
    python scripts/build_pursuer_searched_s3_configs.py --check   fail if stale

All three sweeps carry the same nine rows: the three rows §8 already compares
(B0-blind, B1-ternary ‡, D-dispersive ‡) and the six searched ones. They are in
one sweep rather than three so every comparison sits on identical seeds and pairs
by run index — which is what makes "beats B1 in ≥ 12 of 25 cells" a paired
statement rather than two independent samples.
"""
from __future__ import annotations

import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent

# label -> the search whose best_constants it carries.
SEARCHED = {
    f"S3-{obj}-s{seed}": f"search_s3_pursuer_{obj}_seed{seed}"
    for obj in ("survival", "survival_task")
    for seed in (1, 2, 3)
}

# The three rows §8 already compares, copied verbatim from
# configs/sweeps/pursuer_dispersive.toml so the comparison is against the
# published rows and not against a retyped approximation of them.
REFERENCE = {
    "B0-blind": ('{ kind = "gauci", constants = [-0.7, -1.0, 1.0, -1.0], '
                 'provenance = "enumerated" }', "binary"),
    "B1-ternary": ("TABLE:hand_designed:[[-0.7, -1.0], [1.0, -1.0], [-1.0, -1.0]]", "ternary"),
    "D-dispersive": ("TABLE:hand_designed:[[-0.95, -1.0], [-0.95, -1.0], [-1.0, -1.0]]", "ternary"),
}

FIXED = '''"sim.duration" = 120.0
"pursuer.speed_ratio" = 1.5
"pursuer.confusion_radius" = 0.5'''


def table(provenance: str, pairs) -> str:
    entries = ",\n".join(f"  {{ wheels = [{a:.6f}, {b:.6f}] }}" for a, b in pairs)
    return ('{ kind = "table", memory_bits = 0, provenance = "%s", entries = [\n%s,\n] }'
            % (provenance, entries))


def rows_block() -> str:
    out = []
    for label, (spec, encoding) in REFERENCE.items():
        if spec.startswith("TABLE:"):
            _, prov, pairs = spec.split(":", 2)
            controller = table(prov, json.loads(pairs))
        else:
            controller = spec
        out.append(f'[[rows]]\nlabel = "{label}"\n[rows.overrides]\n{FIXED}\n'
                   f'"sensor.encoding" = "{encoding}"\ncontroller = {controller}\n')
    for label, stem in SEARCHED.items():
        path = REPO / "results" / f"{stem}.json"
        if not path.exists():
            raise SystemExit(f"{path} missing — run `scripts/regenerate_record.sh search_s3` first")
        s = json.loads(path.read_text())
        c = s["best_constants"]
        note = (f'# from results/{stem}.json — objective {s["best_training_objective"]:.4f}, '
                f'optimiser seed {s["seed"]}, training base {s["training_seed_base"]},\n'
                f'# budget {s["budget_evaluations"]} x {s["runs_per_evaluation"]}, '
                f'git {(s.get("git_hash") or "unrecorded")[:12]}, config {s["config_hash"]}')
        out.append(f'[[rows]]\nlabel = "{label}"\n{note}\n[rows.overrides]\n{FIXED}\n'
                   f'"sensor.encoding" = "ternary"\n'
                   f'controller = {table("optimiser_found", list(zip(c[0::2], c[1::2])))}\n')
    return "\n".join(out)


HEAD = '''# EXPERIMENT 1 (freeze lift 1) — is the S = 3 survival advantage the CAPABILITY,
# or the hand-designed rows?
#
# Pre-registered at docs/preregistration/searched-s3-pursuer.md, commit 577f15a.
# GENERATED by scripts/build_pursuer_searched_s3_configs.py — edit that, not this.
#
# Claim G4 is graded SUGGESTED because every S = 3 row in the record is a guess:
# B1, B2 and B3 are hand-written points in six-, ten- and twelve-constant spaces,
# and §5 showed what that costs when it read B2 scoring below B3 as "more sensing
# hurts". Six searched rows — two objectives x three optimiser seeds, each started
# AT B1-ternary's own constants — turn the question into one a search can answer:
# is there better, and does the answer depend on which objective you ask for?
#
# All nine rows are in ONE sweep so every comparison pairs by run index on
# identical seeds. Evaluation seed 20260904, disjoint from the training base
# 930000, so no row is scored on anything it was trained on.
#
# READ SURVIVAL AS MEAN PER-ROBOT SURVIVAL WITH A WILSON INTERVAL, not as a
# median of `survival_fraction`. §12.1 D0 moved the record onto the per-robot
# statistic because the median of a per-run proportion at n = 20 can only land on
# a twentieth: that is how the blind row at 0.47 R came to be published as
# "0.00 [0.00, 0.23]" when 36% of its robots survive.
#
# SATURATION. `survival_fraction` and `capture_rate` both pin once a swarm is
# wiped out. Check the wiped-out share before quoting either, and read
# `time_to_wipeout` in the lethal cells.
'''

MAIN = HEAD + '''#
# THE GRID is `pursuer_dispersive.toml`'s, unchanged: 5 r_p x 5 kappa x 2 h. The
# training class was six of these cells; the other 44 are held out, and the
# pre-registered rule counts the 25 at h = 1.93 s.

name = "pursuer-searched-s3"
base = "../gauci_baseline.toml"
runs_per_cell = 100

[[axis]]
path = "pursuer.range"
values = [0.1, 0.2, 0.35, 0.6, 1.0]

[[axis]]
path = "pursuer.confusion"
values = [0.0, 0.5, 1.0, 2.5, 5.0]

[[axis]]
path = "pursuer.handling_time"
values = [0.39, 1.93]

'''

PARETO = HEAD + '''#
# THE GRID is `pursuer_pareto.toml`'s: the cells §12 reads the two-axis trade-off
# off, where survival has to be plotted against what surviving cost. h = 1.93 s
# throughout, and kappa = 3.0 appears here and nowhere else.

name = "pursuer-searched-s3-pareto"
base = "../gauci_baseline.toml"
runs_per_cell = 100

[[axis]]
path = "pursuer.range"
values = [0.2, 0.35, 1.0]

[[axis]]
path = "pursuer.confusion"
values = [0.0, 3.0]

[[axis]]
path = "pursuer.handling_time"
values = [1.93]

'''


RESCORE = HEAD + '''#
# THE GRID is the TRAINING CLASS, re-scored on held-out seeds: the six conditions
# the searches optimised against, at 100 runs each instead of the 2 an evaluation
# saw. This is the winner's-curse measurement §20 and §21 both insist on — a
# training objective is the minimum of a noisy sample, and §20 found a row
# reporting 1.6009 against an honest 2.6553. The reference rows are carried along
# so the searched rows can be read against something at the same cells.
#
# Evaluation seed 20260904; the searches trained on base 930000, so nothing here
# is scored on a seed it was trained on.

name = "pursuer-searched-s3-rescore"
base = "../gauci_baseline.toml"
runs_per_cell = 100

[[axis]]
path = "pursuer.range"
values = [0.2, 0.35, 0.6]

[[axis]]
path = "pursuer.confusion"
values = [0.5, 2.5]

[[axis]]
path = "pursuer.handling_time"
values = [1.93]

'''


def main() -> int:
    check = "--check" in sys.argv
    body = rows_block()
    status = 0
    for name, head in (("pursuer_searched_s3", MAIN),
                       ("pursuer_searched_s3_pareto", PARETO),
                       ("pursuer_searched_s3_rescore", RESCORE)):
        path = REPO / "configs" / "sweeps" / f"{name}.toml"
        text = head + body
        if check:
            current = path.read_text() if path.exists() else ""
            same = current == text
            print(f"{path.relative_to(REPO)}: {'up to date' if same else 'STALE'}")
            status |= 0 if same else 1
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(REPO)}")
    return status


if __name__ == "__main__":
    raise SystemExit(main())
