#!/usr/bin/env python3
"""Phase 0.4 -- re-execute logged cells and check bit-for-bit reproduction.

This is RE-EXECUTION of existing cells with their logged (seed, run index), not a
new experiment: the base seed, the config and the run indices all come from the
committed sweep configs and the logged run files. Five runs per cell.

Usage: python scripts/verify_determinism.py
"""
from __future__ import annotations
import json, pathlib, subprocess, sys, tomllib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "harness" / "src"))
from swarm_harness.load import load_jsonl  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parent.parent
SCRATCH = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/verify_det")
SCRATCH.mkdir(parents=True, exist_ok=True)

# (section, sweep config, results file, row label, the cell's own axis values)
CELLS = [
    ("9",  "terrain_retune_cost.toml",       "terrain_retune_cost",       "S2-searched",      {"terrain.friction_amplitude": 0.9}),
    ("13", "terrain_tuning_control.toml",    "terrain_tuning_control",    "S2-flat",          {"terrain.friction_amplitude": 0.9}),
    ("14", "terrain_regime_robustness.toml", "terrain_regime_robustness", "S2-rough",         {"terrain.friction_amplitude": 0.9, "start_radius": 0.74, "n": 20}),
    ("15", "terrain_lambda_sweep.toml",      "terrain_lambda_sweep",      "S2-gauci",         {"terrain.correlation_length": 0.0746, "terrain.friction_amplitude": 0.9}),
    ("18", "terrain_lambda_body.toml",       "terrain_lambda_body",       "body-base",        {"terrain.correlation_length": 0.0746, "terrain.friction_amplitude": 0.9}),
    ("19", "terrain_class_eval.toml",        "terrain_class_eval",        "S2-class-flat",    {"terrain.friction_amplitude": 0.9, "start_radius": 0.74, "n": 20}),
    ("21", "phase0_seeds.toml",              "phase0_seeds",              "S2-class-flat-s2", {"terrain.friction_amplitude": 0.9, "start_radius": 0.74, "n": 20}),
]

# fields that are outputs of the simulation rather than inputs
COMPARED = [
    "seed", "final_dispersion", "initial_dispersion", "dispersion_ratio",
    "final_clusters", "final_largest_cluster_fraction", "single_cluster",
    "ever_single_cluster", "fraction_time_single_cluster",
    "time_to_first_single_cluster", "survivors", "survival_fraction",
    "captures", "capture_rate", "realised_fn_rate", "realised_fp_rate",
]

# axis paths that a sweep expresses through a different config key
AXIS_ALIAS = {"start_radius": "swarm.init.radius", "n": "swarm.n"}


def toml_scalar(v):
    """Serialise a Python value as TOML (inline tables and arrays included)."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{k} = {toml_scalar(x)}" for k, x in v.items()) + " }"
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(toml_scalar(x) for x in v) + "]"
    return repr(v)


def one_cell_config(sweep_path: pathlib.Path, row_label: str, axes: dict) -> str:
    spec = tomllib.loads(sweep_path.read_text())
    rows = [r for r in spec.get("rows", []) if r.get("label") == row_label]
    if not rows:
        raise SystemExit(f"row {row_label!r} not in {sweep_path}")
    lines = [
        "# GENERATED by scripts/verify_determinism.py -- one cell of",
        f"# {sweep_path.name}, row {row_label}, five runs. Re-execution, not a new experiment.",
        f'name = {json.dumps(spec["name"])}',
        f'base = {json.dumps(str((sweep_path.parent / spec["base"]).resolve()))}',
        "runs_per_cell = 5",
    ]
    for path, value in axes.items():
        lines += ["", "[[axis]]", f'path = {json.dumps(AXIS_ALIAS.get(path, path))}',
                  f"values = [{toml_scalar(value)}]"]
    # any axis of the original sweep this cell does not pin: keep its first value,
    # which is what the logged cell used when the field is absent from the record.
    pinned = {AXIS_ALIAS.get(p, p) for p in axes}
    for ax in spec.get("axis", []):
        if ax["path"] not in pinned:
            lines += ["", "[[axis]]", f'path = {json.dumps(ax["path"])}',
                      f'values = [{toml_scalar(ax["values"][0])}]']
    r = rows[0]
    lines += ["", "[[rows]]", f'label = {json.dumps(row_label)}', "[rows.overrides]"]
    for k, v in r.get("overrides", {}).items():
        lines.append(f"{json.dumps(k)} = {toml_scalar(v)}")
    return "\n".join(lines) + "\n"


def logged(results: str, row: str, axes: dict, n: int = 5):
    recs = load_jsonl(REPO / "results" / f"{results}.jsonl").filter(row=row, **axes)
    return sorted((r for r in recs.rows if r["run_index"] < n), key=lambda r: r["run_index"])


def main():
    report = []
    for section, cfg, res, row, axes in CELLS:
        conf = SCRATCH / f"cell_s{section}.toml"
        conf.write_text(one_cell_config(REPO / "configs" / "sweeps" / cfg, row, axes))
        out = SCRATCH / f"cell_s{section}.jsonl"
        p = subprocess.run(["cargo", "run", "--quiet", "--release", "--bin", "swarm", "--",
                            "sweep", "-c", str(conf), "-o", str(out)],
                           cwd=REPO, capture_output=True, text=True)
        if p.returncode != 0:
            report.append(dict(section=section, row=row, status="RUN FAILED",
                               detail=(p.stderr or p.stdout)[-400:]))
            continue
        fresh = sorted(load_jsonl(out).rows, key=lambda r: r["run_index"])[:5]
        old = logged(res, row, axes)
        if len(old) != len(fresh):
            report.append(dict(section=section, row=row, status="COUNT MISMATCH",
                               detail=f"logged {len(old)} vs re-executed {len(fresh)}"))
            continue
        diffs = []
        for a, b in zip(old, fresh):
            for k in COMPARED:
                if k in a and k in b and a[k] != b[k]:
                    diffs.append(f"run {a['run_index']} {k}: logged {a[k]!r} vs {b[k]!r}")
        report.append(dict(section=section, row=row,
                           status="IDENTICAL" if not diffs else "DIFFERS",
                           runs=len(old), detail="; ".join(diffs[:6])))
    print(json.dumps(report, indent=1))
    return 0 if all(r["status"] == "IDENTICAL" for r in report) else 1


if __name__ == "__main__":
    raise SystemExit(main())
